#include<sys/stat.h>
#include<stdio.h>
#include<sys/types.h>
#include<unistd.h>
#include<fcntl.h>
#include<sys/wait.h>
#include<string.h>
#include<signal.h>
#include<stdlib.h>
#include<stdbool.h>
#include<pwd.h>
#include<sys/ipc.h>
#include<sys/msg.h>
#include<errno.h>
#include<sys/shm.h>
#include<time.h>
#include<pthread.h>
